
# ----- ETAPA 1: BUILDER -----
FROM node:25-alpine AS builder
WORKDIR /app

# 1. Instala pnpm
RUN npm install -g pnpm

# 2. Copia SÓLO los manifiestos
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./

# 3. Instala las dependencias (Crea la capa de caché)
RUN pnpm install

# 4. Copia el resto del código (Esto BORRARÁ node_modules, como antes)
COPY . .

# 5. --- ¡LA SOLUCIÓN! ---
# Vuelve a ejecutar install. pnpm es inteligente y
# "arreglará" los node_modules que borró el 'COPY . .'
# usará el caché de la tienda (--frozen-lockfile)
RUN pnpm install --frozen-lockfile

# 6. Ahora este build SÍ encontrará tsup
ARG SERVICE_NAME
WORKDIR /app
RUN pnpm --filter ${SERVICE_NAME} build


# ----- ETAPA 2: PRODUCTION -----
FROM node:20-alpine AS production
WORKDIR /app
ARG SERVICE_NAME
COPY --from=builder /app/${SERVICE_NAME}/package.json ./package.json
COPY --from=builder /app/${SERVICE_NAME}/dist ./dist
RUN npm install -g pnpm
RUN pnpm install --prod
CMD ["pnpm", "start"]
