packages:
  - packages/**
  - user-service
  - auth-service
  - product-cat-service
  - cart-service
  - order-service
  - shipping-service
  - payment-service
  - address-service
  - shared

onlyBuiltDependencies:
  - bson
